SQLite3 message, C:\Users\Han\Documents\GitHub\SDI\batch_run\python\sqlite.err open for processing!
