SQLite3 message, C:\Users\Han\Documents\GitHub\SDI\batch_run\python\out\sqlite.err open for processing!
